version: '3.1'

services:

  wordpress:
    depends_on: 
      - db
    image: wordpress:latest
    ports:
      - 8080:80
    restart: always
    volumes:
      - ./wp-content/:/var/www/html/wp-content 
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpboss
      WORDPRESS_DB_PASSWORD: k@i&9dJFD#S#dsf3lj2D
      WORDPRESS_DB_NAME: wordpress
    networks:
      - back

  db:
    image: mysql:5.7
    restart: always
    volumes:
       - ./db-data/:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpboss
      MYSQL_PASSWORD: k@i&9dJFD#S#dsf3lj2D
      MYSQL_RANDOM_ROOT_PASSWORD: 'H39Dei323jID@#' 
    networks:
      - back
  
  phpmyadmin:
    depends_on:
       - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 9000:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 'H39Dei323jID@#' 
    networks:
      - back

networks:
   back:

